import { writeFile } from 'fs/promises';
import { join } from 'path';
import { formatTimestamp } from '@tillerstead/shared';
import type { AgentResult } from '@tillerstead/shared';

export async function generateReport(
  rootPath: string,
  auditResults: any,
  outputPath?: string
): Promise<AgentResult<string>> {
  try {
    const timestamp = new Date().toISOString().split('T')[0];
    const reportPath = outputPath || join(rootPath, '_reports', `audit-${timestamp}.md`);
    
    const report = `# Tillerstead.com Site Audit Report
Generated: ${formatTimestamp()}

## Executive Summary
- **Total Issues:** ${auditResults.summary?.totalIssues || 0}
- **Critical Issues:** ${auditResults.summary?.criticalIssues || 0}
- **Warnings:** ${auditResults.summary?.warnings || 0}

## Jekyll Includes Analysis
${JSON.stringify(auditResults.jekyll || {}, null, 2)}

## SEO Analysis
${JSON.stringify(auditResults.seo || {}, null, 2)}

## Performance Metrics
${JSON.stringify(auditResults.performance || {}, null, 2)}

## Accessibility Audit
${JSON.stringify(auditResults.accessibility || {}, null, 2)}

## Recommendations
- Review critical issues immediately
- Address warnings in next sprint
- Schedule follow-up audit in 30 days

---
*Generated by Tillerstead MCP Agents System*
`;
    
    if (outputPath !== 'stdout') {
      await writeFile(reportPath, report, 'utf-8');
    }
    
    return {
      success: true,
      data: outputPath === 'stdout' ? report : reportPath,
      timestamp: formatTimestamp(),
    };
  } catch (error) {
    return {
      success: false,
      errors: [error instanceof Error ? error.message : String(error)],
      timestamp: formatTimestamp(),
    };
  }
}
